### ISSUE TITLE
FloatingPointError: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by kexul** [JMorado/ParaMol#66]
Hi, I did a torsion scan with my own molecule with paramol but the following error occured: 
```
Traceback (most recent call last):
  File "/root/repo/prepare/paramol.py", line 85, in <module>
    systems, parameter_space, objective_function, optimizer = parametrization.run_task(paramol_settings, [norfloxacin])
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Tasks/parametrization.py", line 109, in run_task
    objective_function.f(parameter_space.optimizable_parameters_values_scaled, opt_mode=False)
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Objective_function/objective_function.py", line 325, in f
    objective_function = self.calculate_objective_function(parameters_values, fmm, emm, esp)
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Objective_function/objective_function.py", line 196, in calculate_objective_function
    energy_decomposed = property.calculate_property(emm)
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Objective_function/Properties/energy_property.py", line 109, in calculate_property
    obj_fun_energies.append(obj_fun / var)
FloatingPointError: invalid value encountered in double_scalars
```
I've print the `obj_fun` and `var`, they were `0`.

Here is the code and files I've used, which was basically copied from the example. 
[RB2345_AC.zip](https://github.com/JMorado/ParaMol/files/6546535/RB2345_AC.zip)

```
    openmm_system = OpenMMEngine(init_openmm=True, topology_format='AMBER',
                                    
 top_file='RB2345_AC.prmtop', 
                                    crd_format='AMBER',
                                    crd_file='RB2345_AC.inpcrd')
    # Create ParaMol System
    norfloxacin = ParaMolSystem(name="norfloxacin", engine=openmm_system, n_atoms=54)

    # Create ParaMol's force field representation
    norfloxacin.force_field.create_force_field()

    # Create ParaMol settings instance
    paramol_settings = Settings()

    # The objective function will contain an energy and a regularization term
    paramol_settings.properties["include_energies"] = True
    paramol_settings.properties["include_forces"] = False # One should not include forces when a torsional scan
    paramol_settings.properties["include_regularization"] = True

    # --------------------------------------------------------- #
    #                Symmetrize ParaMol ForceField              #
    # --------------------------------------------------------- #
    # Symmetry ParaMol ForceField so that it respects atom-type symmetries
    amber_symmetrizer = AmberSymmetrizer(top_file="RB2345_AC.prmtop")
    amber_symmetrizer.get_symmetries()
    amber_symmetrizer.symmetrize_force_field(norfloxacin.force_field)

    # --------------------------------------------------------- #
    #                     Set the QM Engine                     #
    # --------------------------------------------------------- #
    # Create the ASE calculator
    from ase.calculators.dftb import *

    calc = Dftb(Hamiltonian_='DFTB',  # line is included by default
                Hamiltonian_MaxAngularMomentum_='',
                Hamiltonian_MaxAngularMomentum_H='s',
                Hamiltonian_MaxAngularMomentum_O='p',
                Hamiltonian_MaxAngularMomentum_C='p',
                Hamiltonian_MaxAngularMomentum_N="p",
                Hamiltonian_MaxAngularMomentum_F="p",
                Hamiltonian_Dispersion="DftD3 { \n s6=1.000 \n s8=0.5883 \n Damping = BeckeJohnson { \n a1=0.5719 \n a2=3.6017 \n } \n }",
                Hamiltonian_SCC='Yes',
                Hamiltonian_SCCTolerance=1e-8, 
                slako_dir='/data/halorg-0-1/')

    # Alternative, we could set the calculator in the settings
    paramol_settings.qm_engine["ase"]["calculator"] = calc

    # --------------------------------------------------------- #
    #                  Perform the Torsional Scan               #
    # --------------------------------------------------------- #
    torsion_to_scan = [[27, 28, 29, 30]]
    scan_settings = [[-180.0, 180.0, 90.0]]
    torsion_scan = TorsionScan()
    torsion_scan.run_task(paramol_settings, [norfloxacin], torsion_to_scan, scan_settings, optimize_qm_before_scan=True)

    # Save coordinates and energies into .nc file
    norfloxacin.write_data("norfloxacin_scan.nc")
    # --------------------------------------------------------- #
    #                   Parametrize the Torsion                 #
    # --------------------------------------------------------- #
    norfloxacin.force_field.optimize_torsions_by_symmetry(torsion_to_scan)
    norfloxacin.force_field.write_ff_file("norfloxacin_symm.ff")

    parametrization = Parametrization()
    systems, parameter_space, objective_function, optimizer = parametrization.run_task(paramol_settings, [norfloxacin])

    # Update AMBER symmetrizer with new parameters
    amber_symmetrizer.update_term_types_parameters(parameter_space.optimizable_parameters)

    # Write AMBER topology file (.prmtop) and .frcmod file
    amber_symmetrizer.save("norfloxacin_opt.prmtop")
    amber_symmetrizer.save_frcmod("norfloxacin_opt.frcmod")
```

**Comment by JMorado** [comment]
Hi,

If you look at the "norfloxacin_sym.ff" produced after you set that you want to optimize all torsions that share the same symmetry with torsion_to_scan (norfloxacin.force_field.optimize_torsions_by_symmetry(torsion_to_scan)), you get the following for the torsions:

```
PeriodicTorsionForce   2 
  0   0   1   2  36       1.00000000       0.00000000       8.36800000   0   0   0   T1 
  1   0   1   2  36       2.00000000       3.14159400      10.46000000   0   0   0   T0 
  2   0   1  24  50       1.00000000       0.00000000       8.36800000   0   0   0   T1 
  3   0   1  24  50       2.00000000       3.14159400      10.46000000   0   0   0   T0 
  4   2   1  24  50       2.00000000       3.14159400      10.46000000   0   0   0   T0 
  5   2   3  23  49       2.00000000       3.14159400      15.16700000   0   0   0   T3 
  6   2   3   4  37       2.00000000       3.14159400      15.16700000   0   0   0   T3 
  7   3   4   5  38       2.00000000       3.14159400      15.16700000   0   0   0   T3 
  8   4   3   2  36       2.00000000       3.14159400       1.88280000   0   0   0   T4 
  9   4   3  23  49       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 10   4   5   6  39       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 11   6   5   4  37       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 12   6   7  23  49       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 13   7   6   5  38       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 14   7   8   9  40       2.00000000       3.14159400      16.73600000   0   0   0   T6 
 15   8   7   6  39       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 16   8   7  23  49       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 17   8  22  21  48       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 18   8   9  10  41       2.00000000       3.14159400       7.11280000   0   0   0   T7 
 19  11  10   9  40       2.00000000       3.14159400       7.11280000   0   0   0   T7 
 20  11  22  21  48       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 21  11  12  13  42       2.00000000       3.14159400      20.08320000   0   0   0   T9 
 22  12  11  10  41       2.00000000       3.14159400       1.25520000   0   0   0   T8 
 23  13  14  21  48       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 24  14  15  20  47       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 25  14  15  16  43       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 26  15  14  13  42       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 27  15  14  21  48       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 28  15  20  19  46       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 29  15  16  17  44       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 30  16  15  20  47       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 31  16  17  18  45       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 32  17  18  19  46       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 33  18  17  16  43       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 34  18  19  20  47       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 35  19  18  17  44       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 36  20  15  16  43       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 37  20  19  18  45       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 38  21  14  13  42       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 39  22   8   9  40       2.00000000       3.14159400      16.73600000   0   0   0   T6 
 40  22  11  10  41       2.00000000       3.14159400       1.25520000   0   0   0   T8 
 41  23   3   2  36       2.00000000       3.14159400       1.88280000   0   0   0   T4 
 42  23   3   4  37       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 43  23   7   6  39       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 44  24   1   2  36       2.00000000       3.14159400      10.46000000   0   0   0   T0 
 45  24  25  26  51       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 46  25  34  33  53       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 47  26  25  24  50       2.00000000       3.14159400       1.88280000   0   0   0   T4 
 48  26  27  32  52       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 49  27  32  33  53       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 50  28  27  26  51       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 51  28  27  32  52       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 52  32  27  26  51       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 53  34  25  24  50       2.00000000       3.14159400       1.88280000   0   0   0   T4 
 54  34  25  26  51       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 55  34  33  32  52       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 56  35  34  33  53       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 57  37   4   5  38       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 58  38   5   6  39       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 59  40   9  10  41       2.00000000       3.14159400       7.11280000   0   0   0   T7 
 60  43  16  17  44       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 61  44  17  18  45       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 62  45  18  19  46       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 63  46  19  20  47       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 64  52  32  33  53       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 65   1   3   2  36       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 66   3   5   4  37       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 67   4   6   5  38       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 68   5   7   6  39       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 69   8  40   9  10       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 70  11   9  10  41       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 71  14  42  13  12       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 72  17  15  16  43       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 73  16  18  17  44       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 74  17  19  18  45       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 75  18  20  19  46       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 76  19  15  20  47       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 77  22  14  21  48       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 78   3   7  23  49       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 79   1  25  24  50       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 80  25  27  26  51       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 81  27  33  32  52       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 82  32  34  33  53       2.00000000       3.14159400       4.60240000   0   0   0   T13 
 83   0   1   2   3       2.00000000       3.14159400      10.46000000   0   0   0   T0 
 84   0   1  24  25       2.00000000       3.14159400      10.46000000   0   0   0   T0 
 85   1   2   3  23       2.00000000       3.14159400       3.97480000   0   0   0   T2 
 86   1   2   3   4       2.00000000       3.14159400       3.97480000   0   0   0   T2 
 87   1  24  25  34       2.00000000       3.14159400       3.97480000   0   0   0   T2 
 88   1  24  25  26       2.00000000       3.14159400       3.97480000   0   0   0   T2 
 89   2   1  24  25       2.00000000       3.14159400      10.46000000   0   0   0   T0 
 90   2   3  23   7       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 91   2   3   4   5       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 92   3   2   1  24       2.00000000       3.14159400      10.46000000   0   0   0   T0 
 93   3  23   7   6       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 94   3  23   7   8       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 95   3   4   5   6       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 96   4   3  23   7       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 97   4   5   6   7       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 98   5   4   3  23       2.00000000       3.14159400      15.16700000   0   0   0   T3 
 99   5   6   7   8       2.00000000       3.14159400      15.16700000   0   0   0   T3 
100   5   6   7  23       2.00000000       3.14159400      15.16700000   0   0   0   T3 
101   6   7   8  22       2.00000000       3.14159400       2.11292000   0   0   0   T5 
102   6   7   8   9       2.00000000       3.14159400       2.11292000   0   0   0   T5 
103   7   8  22  11       2.00000000       3.14159400       2.11292000   0   0   0   T5 
104   7   8  22  21       2.00000000       3.14159400       2.11292000   0   0   0   T5 
105   7   8   9  10       2.00000000       3.14159400      16.73600000   0   0   0   T6 
106   8  22  11  10       2.00000000       3.14159400      15.16700000   0   0   0   T3 
107   8  22  11  12       2.00000000       3.14159400      15.16700000   0   0   0   T3 
108   8  22  21  14       2.00000000       3.14159400      15.16700000   0   0   0   T3 
109   8   9  10  11       2.00000000       3.14159400       7.11280000   0   0   0   T7 
110   9   8   7  23       2.00000000       3.14159400       2.11292000   0   0   0   T5 
111   9   8  22  11       2.00000000       3.14159400       2.11292000   0   0   0   T5 
112   9   8  22  21       2.00000000       3.14159400       2.11292000   0   0   0   T5 
113   9  10  11  22       2.00000000       3.14159400       1.25520000   0   0   0   T8 
114   9  10  11  12       2.00000000       3.14159400       1.25520000   0   0   0   T8 
115  10   9   8  22       2.00000000       3.14159400      16.73600000   0   0   0   T6 
116  10  11  22  21       2.00000000       3.14159400      15.16700000   0   0   0   T3 
117  10  11  12  13       2.00000000       3.14159400      20.08320000   0   0   0   T9 
118  11  22  21  14       2.00000000       3.14159400      15.16700000   0   0   0   T3 
119  11  12  13  14       2.00000000       3.14159400      20.08320000   0   0   0   T9 
120  12  11  22  21       2.00000000       3.14159400      15.16700000   0   0   0   T3 
121  12  13  14  15       2.00000000       3.14159400      15.16700000   0   0   0   T3 
122  12  13  14  21       2.00000000       3.14159400      15.16700000   0   0   0   T3 
123  13  12  11  22       2.00000000       3.14159400      20.08320000   0   0   0   T9 
124  13  14  15  20       2.00000000       3.14159400       3.32628000   0   0   0   T10 
125  13  14  15  16       2.00000000       3.14159400       3.32628000   0   0   0   T10 
126  13  14  21  22       2.00000000       3.14159400      15.16700000   0   0   0   T3 
127  14  15  20  19       2.00000000       3.14159400      15.16700000   0   0   0   T3 
128  14  15  16  17       2.00000000       3.14159400      15.16700000   0   0   0   T3 
129  15  14  21  22       2.00000000       3.14159400      15.16700000   0   0   0   T3 
130  15  20  19  18       2.00000000       3.14159400      15.16700000   0   0   0   T3 
131  15  16  17  18       2.00000000       3.14159400      15.16700000   0   0   0   T3 
132  16  15  14  21       2.00000000       3.14159400       3.32628000   0   0   0   T10 
133  16  15  20  19       2.00000000       3.14159400      15.16700000   0   0   0   T3 
134  16  17  18  19       2.00000000       3.14159400      15.16700000   0   0   0   T3 
135  17  16  15  20       2.00000000       3.14159400      15.16700000   0   0   0   T3 
136  17  18  19  20       2.00000000       3.14159400      15.16700000   0   0   0   T3 
137  20  15  14  21       2.00000000       3.14159400       3.32628000   0   0   0   T10 
138  22   8   7  23       2.00000000       3.14159400       2.11292000   0   0   0   T5 
139  24  25  34  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
140  24  25  34  35       2.00000000       3.14159400      15.16700000   0   0   0   T3 
141  24  25  26  27       2.00000000       3.14159400      15.16700000   0   0   0   T3 
142  25  34  33  32       2.00000000       3.14159400      15.16700000   0   0   0   T3 
143  25  26  27  28       2.00000000       3.14159400      15.16700000   0   0   0   T3 
144  25  26  27  32       2.00000000       3.14159400      15.16700000   0   0   0   T3 
145  26  25  34  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
146  26  25  34  35       2.00000000       3.14159400      15.16700000   0   0   0   T3 
147  26  27  28  29       2.00000000       0.00000000       0.00000000   0   0   0   T11 
148  26  27  28  30       2.00000000       0.00000000       0.00000000   0   0   0   T11 
149  26  27  28  31       2.00000000       0.00000000       0.00000000   0   0   0   T11 
150  26  27  32  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
151  27  26  25  34       2.00000000       3.14159400      15.16700000   0   0   0   T3 
152  27  32  33  34       2.00000000       3.14159400      15.16700000   0   0   0   T3 
153  28  27  32  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
154  29  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
155  30  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
156  31  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
157  32  33  34  35       2.00000000       3.14159400      15.16700000   0   0   0   T3 
158   0   1  24   2       2.00000000       3.14159400      43.93200000   0   0   0   T12 
159   4  23   3   2       2.00000000       3.14159400       4.60240000   0   0   0   T13 
160   6  23   7   8       2.00000000       3.14159400       4.60240000   0   0   0   T13 
161   7  22   8   9       2.00000000       3.14159400       4.60240000   0   0   0   T13 
162  22  10  11  12       2.00000000       3.14159400       4.60240000   0   0   0   T13 
163  13  21  14  15       2.00000000       3.14159400       4.60240000   0   0   0   T13 
164  16  20  15  14       2.00000000       3.14159400       4.60240000   0   0   0   T13 
165  11  21  22   8       2.00000000       3.14159400       4.60240000   0   0   0   T13 
166  26  34  25  24       2.00000000       3.14159400       4.60240000   0   0   0   T13 
167  26  32  27  28       2.00000000       3.14159400       4.60240000   0   0   0   T13 
168  25  33  34  35       2.00000000       3.14159400       4.60240000   0   0   0   T13
```

Clearly, there is no torsion in the topology that is formed by the quartet of atoms [27, 28, 29, 30]. Therefore, ParaMol is not able to identify its symmetry, and then the optimization will try to fit 0 parameters, hence the error.

Try to choose a torsion that is listed, even if that is not the one you've scanned (they should be related, though...).

I will add some assertions and more verbose to try to minimize these errors.

Best,
João

**Comment by kexul** [comment]
Hi, @JMorado , thanks for the quick reply!

The `prmtop` and `inpcrd` file was generated by `acpype`( which use ambertools). The purpose I use `Paramol`  was to fill up the missing parameters of `gaff`. Is this the correct usage of paramol?

**Comment by JMorado** [comment]
Yes, you can optimize any parameters that are contained in the `prmtop` file, but it seems that the 27-28-29-30 is not there. 

The reason for that may be that that specific dihedral has a force constant of 0 and, therefore, it is not included in the `prmtop` file because it does not contribute to the energy. What I usually do in these situations is to change the force constant in the `frcmod` file to, for example, 0.001. Leap will then include it in the `prmtop` file.

The same argument works for two different dihedrals with the same parameters. Say you have the following lines in the `frcmod` file:

```
ca-ca-ca-c3    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-f     1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
```

To save memory, LEAP assumes that these share the same symmetry. If you want to optimize them independently you'll have to change the `frcmod` to something like:

```
ca-ca-ca-c3    1     3.6251  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-f     1     3.6250  180.000   2.0    SCEE=1.2 SCNB=2.0
```
Note the small change in force constant. LEAP then assumes that these are two different dihedral types, and they will appear as so in the `prmtop` file.

Hope this helps.

**Comment by JMorado** [comment]
Actually, I think the dihedrals with force constant 0 were included in the prmtop file. If you look at these lines in the .ff file:

```
147  26  27  28  29       2.00000000       0.00000000       0.00000000   0   0   0   T11 
148  26  27  28  30       2.00000000       0.00000000       0.00000000   0   0   0   T11 
149  26  27  28  31       2.00000000       0.00000000       0.00000000   0   0   0   T11 
```

These are dihedrals with a force constant of 0. The  26-27-28-30 and 26-27-28-31 are c-c-c-f whereas 26-27-28-31 is c-c-c-c. They share the same symmetry, but you may want to break it with the procedure I explained in the previous message.

You can then use the dihedral scan you generated to optimize the c-c-c-f dihedral parameters of the 26-27-28-30 and 26-27-28-31 dihedrals. Set them for optimization using:

```
norfloxacin.force_field.optimize_torsions_by_symmetry([[26,27,38,30]])
```

**Comment by JMorado** [comment]
Let me know if you have any further questions.

**Comment by kexul** [comment]
Hi @JMorado , I tried modify the `frcmod` file and generate a new `prmtop` file. Then use `paramol` to optimize the parameters but an error occurred:
```
Writing norfloxacin_scan_1d_torsion_27_22_23_24.nc file for system norfloxacin.
Traceback (most recent call last):
  File "/root/repo/prepare/paramol.py", line 77, in <module>
    torsion_scan.run_task(paramol_settings, [norfloxacin], torsion_to_scan, scan_settings, optimize_qm_before_scan=True)
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Tasks/torsions_scan.py", line 198, in run_task
    system.write_data(file_name + ".nc")
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/System/system.py", line 670, in write_data
    data_coordinates[:] = self.ref_coordinates
  File "netCDF4/_netCDF4.pyx", line 4853, in netCDF4._netCDF4.Variable.__setitem__
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/netCDF4/utils.py", line 365, in _StartCountStride
    datashape = broadcasted_shape(shape, datashape)
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/netCDF4/utils.py", line 973, in broadcasted_shape
    return np.broadcast(a, b).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

Here is my modified `frcmod` and `prmtop` file:
[new.zip](https://github.com/JMorado/ParaMol/files/6551612/new.zip)
I add new lines in frcmod file to enforce two new dihedral :
![image](https://user-images.githubusercontent.com/5920217/119777805-43e2c000-bef9-11eb-8d0f-a8d84ae828e0.png)

**Comment by kexul** [comment]
Hi @JMorado , I've tried modify the `frcmod` file, add a small force constant,  and use tleap to generate an new `prmtop` file, but the dihedral `ca-ca-c3-f` was still not included in the generate `norfloxacin_sym.ff` file.

**Comment by kexul** [comment]
Besides, I used atom index from 1 as in pdb file.  In the `.ff` file, the atom index was started from 0, should I set `torsion_to_scan` parameter using atom index started from zero?

**Comment by JMorado** [comment]
Hi @kexul . 
I think the ca-ca-c3-f dihedrals are already included. From what I can see, these are the dihedrals you are interested in (numbering does not match with the figure above):

```
114  20  21  22  23       2.00000000       3.14159400       0.00418400   0   0   0   T10 
115  20  21  22  24       2.00000000       3.14159400       0.00418400   0   0   0   T10 
116  20  21  22  25       2.00000000       3.14159400       0.00418400   0   0   0   T10 
117  23  22  21  26       2.00000000       3.14159400       0.00418400   0   0   0   T10 
118  24  22  21  26       2.00000000       3.14159400       0.00418400   0   0   0   T10 
119  25  22  21  26       2.00000000       3.14159400       0.00418400   0   0   0   T10 
```

And actually, I have just re-checked, and they were also already included in the `RB2345_AC.prmtop` (see T11 symmetries):

```
147  26  27  28  29       2.00000000       0.00000000       0.00000000   0   0   0   T11 
148  26  27  28  30       2.00000000       0.00000000       0.00000000   0   0   0   T11 
149  26  27  28  31       2.00000000       0.00000000       0.00000000   0   0   0   T11 
150  26  27  32  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
151  27  26  25  34       2.00000000       3.14159400      15.16700000   0   0   0   T3 
152  27  32  33  34       2.00000000       3.14159400      15.16700000   0   0   0   T3 
153  28  27  32  33       2.00000000       3.14159400      15.16700000   0   0   0   T3 
154  29  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
155  30  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
156  31  28  27  32       2.00000000       0.00000000       0.00000000   0   0   0   T11 
```

The numbering in the figure was what led me to think that the T11 dihedrals belonged to different dihedral types. They actually do not! So you are good to go and scan one of those T11 dihedral. Just remember that ParaMol starts atom indexing from 0.

Furthermore, in the `new` files you've sent me, it wasn't actually necessary to break the symmetry of the  `ca-ca-c3-f` and `f -c3-ca-ca` because they already have different parameters and, therefore, are considered to be different dihedral types. That only applied to dihedral types like these:

```
ca-ca-cd-cc   1    0.505       180.000           2.000      same as c2-ce-ca-ca, penalty score=229.0
ca-ca-cd-ca   1    0.505       180.000           2.000      same as c2-ce-ca-ca, penalty score=229.0
``

So, if you wanted to indepently optimize the parameters of the `ca-ca-cd-cc` and  `ca-ca-cd-ca`, you'd have to break their symmetry.

Best,
João

**Comment by kexul** [comment]
Wow, thanks so much for your continued help! The new atom index worked like a charm.

**Comment by kexul** [comment]
Hi @JMorado ,  the parametrization terminated successfully! But when I check the `frcmod` file generated, the value of `ca-ca-c3-f` seems very different from other values. 
```
ca-ca-ca-c3    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-f     1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-c3-f     1   -11.26833001   13.696   2.0    SCEE=1.2 SCNB=2.0
nv-ca-ca-ha    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-ha    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
hn-nv-ca-ca    1     1.05000000  180.000   2.0    SCEE=1.2 SCNB=2.0
```

Is this a good result?

Here is part of my output when running paramol:

```
ata of system norfloxacin was written to file norfloxacin_scan.nc
!=================================================================================!
!                                 PARAMETRIZATION                                 !
!=================================================================================!
!=================================================================================!
!                                Scaling Constants                                !
! Term type                     Value                                             !
!---------------------------------------------------------------------------------!
! torsion_phase                 3.14159265                                        !
! torsion_k                     16.73600000                                       !
!=================================================================================!
!=================================================================================!
!                                   Prior Widths                                  !
! Term type                     Value                                             !
!---------------------------------------------------------------------------------!
! torsion_phase                 3.14159265                                        !
! torsion_k                     16.73600000                                       !
!=================================================================================!
!=================================================================================!
!                           Objective Function Analysis                           !
! PROPERTY                       Value      x     Weight      =   Contribution    !
!---------------------------------------------------------------------------------!
! ENERGY                      63.34887833       1.00000000        63.34887833     !
! REGULARIZATION              0.00000000        1.00000000        0.00000000      !
! TOTAL                                                           63.34887833     !
!---------------------------------------------------------------------------------!
! Function Evaluations:    0         Time (s):                0.002               !
!=================================================================================!

Using 4 structures in the optimization.
Number of parameters to be optimized: 2.
ParaMol will perform unconstrained optimization.
!=================================================================================!
!                           STARTING SCIPY OPTIMIZER                              !
!=================================================================================!
/data/miniconda3/envs/uii/lib/python3.7/site-packages/scipy/optimize/_minimize.py:525: RuntimeWarning: Method SLSQP does not use Hessian information (hess).
  RuntimeWarning)
/data/miniconda3/envs/uii/lib/python3.7/site-packages/ParaMol/Optimizers/scipy_optimizers.py:67: OptimizeWarning: Unknown solver options: verbosity
  optimization = minimize(fun=f, x0=parameters, **self.__dict__)
  NIT    FC           OBJFUN            GNORM
    1     4     6.520047E+03     3.461633E+01
    2     8     1.334427E+05     8.956616E+01
    3    14     1.373651E+01     1.646591E+01
    4    17     1.369743E+01     8.671029E+00
    5    20     1.369652E+01     1.305434E+00
    6    23     1.369652E+01     4.902052E-03
Optimization terminated successfully    (Exit mode 0)
            Current function value: 13.696521568505162
            Iterations: 6
            Function evaluations: 32
            Gradient evaluations: 6
!=================================================================================!
!                      SCIPY OPTIMIZER TERMINATED SUCCESSFULLY! :)                !
!=================================================================================!
!=================================================================================!
!                           Objective Function Analysis                           !
! PROPERTY                       Value      x     Weight      =   Contribution    !
!---------------------------------------------------------------------------------!
! ENERGY                      5.75477795        1.00000000        5.75477795      !
! REGULARIZATION              7.94174362        1.00000000        7.94174362      !
! TOTAL                                                           13.69652157     !
!---------------------------------------------------------------------------------!
! Function Evaluations:    32        Time (s):                0.002               !
!=================================================================================!

!=================================================================================!
!                   PARAMETRIZATION TERMINATED SUCCESSFULLY :)                    !
!=================================================================================!
```

**Comment by JMorado** [comment]
Parameters are usually very dependent on the system, but I would say that those are really large values...

If these are the `scan_settings = [[-180.0, 180.0, 90.0]]` you are using, then you should definitely decrease the spacing to something to something like `[[-180.0, 180.0, 10.0]]`

Also, I recommend using Boltzmann or Non-Boltzmann weighting to weight the conformations in the optimization:

```
paramol_settings.objective_function["weighting_method"] = "boltzmann"
paramol_settings.objective_function["weighting_temperature"] = 300.0*unit.kelvin
```

DFTB works fine for some initial tests, but the final results should be computed using higher levels of theory.

You can plot the results also to see how they look like. The scan QM energies are stored in `norfloxacin.ref_energies` and the MM energies before and after the optimization can be computed calling the method `norfloxacin.get_energies_ensemble()`

Off the top of my head, these are some of the aspects that may help you improve the parameterizations...

**Comment by kexul** [comment]
Thanks @JMorado . I've tried decrease the spacing and use boltzmann, now it becomes even larger...
```
ca-ca-ca-c3    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-f     1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-c3-f     1   -14.32510008  -31.655   2.0    SCEE=1.2 SCNB=2.0
nv-ca-ca-ha    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
ca-ca-ca-ha    1     3.62500000  180.000   2.0    SCEE=1.2 SCNB=2.0
hn-nv-ca-ca    1     1.05000000  180.000   2.0    SCEE=1.2 SCNB=2.0
```

**Comment by JMorado** [comment]
I advise you to look at the plots of the scans. It's impossible to understand if that is a good or bad result without that.
